// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddRecentPath(arg1:number,arg2:string):Promise<void>;

export function AutoSaveCommand(arg1:number,arg2:string):Promise<void>;

export function ClearAllTerminals():Promise<void>;

export function ClearRecentPaths(arg1:number):Promise<void>;

export function CloseTerminal(arg1:string):Promise<void>;

export function CreateCommand(arg1:models.Command):Promise<void>;

export function CreateCommandGroup(arg1:models.CommandGroup):Promise<void>;

export function CreateTerminal(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function CreateWorkspace(arg1:string,arg2:string):Promise<models.Workspace>;

export function DatabaseHasData():Promise<boolean>;

export function DeleteCommand(arg1:number):Promise<void>;

export function DeleteCommandGroup(arg1:number):Promise<void>;

export function DeleteRecentPath(arg1:number):Promise<void>;

export function DeleteWorkspace(arg1:number):Promise<void>;

export function ExportDatabase():Promise<models.DatabaseBackup>;

export function ExportWorkspace(arg1:number):Promise<models.WorkspaceExport>;

export function GetCommandGroups(arg1:number):Promise<Array<models.CommandGroup>>;

export function GetCommands(arg1:number):Promise<Array<models.Command>>;

export function GetDirectoryPath(arg1:string):Promise<string>;

export function GetRecentPaths(arg1:number):Promise<Array<models.RecentPath>>;

export function GetWorkspaces():Promise<Array<models.Workspace>>;

export function ImportDatabase(arg1:models.DatabaseBackup):Promise<void>;

export function ImportWorkspace(arg1:models.WorkspaceExport,arg2:string):Promise<models.Workspace>;

export function OpenDatabaseBackupDialog():Promise<string>;

export function OpenDirectorySelectorDialog():Promise<string>;

export function OpenFileDialog():Promise<string>;

export function OpenFileSelectorDialog():Promise<string>;

export function OpenWorkspaceWindow(arg1:number):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SaveDatabaseBackupDialog(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SelectPathDialog():Promise<string>;

export function SetCurrentWorkspace(arg1:number):Promise<void>;

export function UpdateCommand(arg1:models.Command):Promise<void>;

export function UpdateCommandGroup(arg1:models.CommandGroup):Promise<void>;

export function UpdateWorkspace(arg1:models.Workspace):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;

export function WriteTerminal(arg1:string,arg2:string):Promise<void>;
