// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentPath(arg1, arg2) {
  return window['go']['main']['App']['AddRecentPath'](arg1, arg2);
}

export function AutoSaveCommand(arg1, arg2) {
  return window['go']['main']['App']['AutoSaveCommand'](arg1, arg2);
}

export function ClearAllTerminals() {
  return window['go']['main']['App']['ClearAllTerminals']();
}

export function ClearRecentPaths(arg1) {
  return window['go']['main']['App']['ClearRecentPaths'](arg1);
}

export function CloseTerminal(arg1) {
  return window['go']['main']['App']['CloseTerminal'](arg1);
}

export function CreateCommand(arg1) {
  return window['go']['main']['App']['CreateCommand'](arg1);
}

export function CreateCommandGroup(arg1) {
  return window['go']['main']['App']['CreateCommandGroup'](arg1);
}

export function CreateTerminal(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateTerminal'](arg1, arg2, arg3, arg4);
}

export function CreateWorkspace(arg1, arg2) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2);
}

export function DatabaseHasData() {
  return window['go']['main']['App']['DatabaseHasData']();
}

export function DeleteCommand(arg1) {
  return window['go']['main']['App']['DeleteCommand'](arg1);
}

export function DeleteCommandGroup(arg1) {
  return window['go']['main']['App']['DeleteCommandGroup'](arg1);
}

export function DeleteRecentPath(arg1) {
  return window['go']['main']['App']['DeleteRecentPath'](arg1);
}

export function DeleteWorkspace(arg1) {
  return window['go']['main']['App']['DeleteWorkspace'](arg1);
}

export function ExportDatabase() {
  return window['go']['main']['App']['ExportDatabase']();
}

export function ExportWorkspace(arg1) {
  return window['go']['main']['App']['ExportWorkspace'](arg1);
}

export function GetCommandGroups(arg1) {
  return window['go']['main']['App']['GetCommandGroups'](arg1);
}

export function GetCommands(arg1) {
  return window['go']['main']['App']['GetCommands'](arg1);
}

export function GetDirectoryPath(arg1) {
  return window['go']['main']['App']['GetDirectoryPath'](arg1);
}

export function GetRecentPaths(arg1) {
  return window['go']['main']['App']['GetRecentPaths'](arg1);
}

export function GetWorkspaces() {
  return window['go']['main']['App']['GetWorkspaces']();
}

export function ImportDatabase(arg1) {
  return window['go']['main']['App']['ImportDatabase'](arg1);
}

export function ImportWorkspace(arg1, arg2) {
  return window['go']['main']['App']['ImportWorkspace'](arg1, arg2);
}

export function OpenDatabaseBackupDialog() {
  return window['go']['main']['App']['OpenDatabaseBackupDialog']();
}

export function OpenDirectorySelectorDialog() {
  return window['go']['main']['App']['OpenDirectorySelectorDialog']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFileSelectorDialog() {
  return window['go']['main']['App']['OpenFileSelectorDialog']();
}

export function OpenWorkspaceWindow(arg1) {
  return window['go']['main']['App']['OpenWorkspaceWindow'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SaveDatabaseBackupDialog(arg1) {
  return window['go']['main']['App']['SaveDatabaseBackupDialog'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SelectPathDialog() {
  return window['go']['main']['App']['SelectPathDialog']();
}

export function SetCurrentWorkspace(arg1) {
  return window['go']['main']['App']['SetCurrentWorkspace'](arg1);
}

export function UpdateCommand(arg1) {
  return window['go']['main']['App']['UpdateCommand'](arg1);
}

export function UpdateCommandGroup(arg1) {
  return window['go']['main']['App']['UpdateCommandGroup'](arg1);
}

export function UpdateWorkspace(arg1) {
  return window['go']['main']['App']['UpdateWorkspace'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}

export function WriteTerminal(arg1, arg2) {
  return window['go']['main']['App']['WriteTerminal'](arg1, arg2);
}
